### ISSUE TITLE
run-python

### ISSUE THREAD

**Issue by Pitometsu** [pwalsh/pipenv.el#8] opened 2018-01-21 13:10 UTC
Thank you for this new plugin, progress amazes.
I'm trying to test it a little now.

`M-x run-python`
```
apply: Searching for program: No such file or directory, ipython
```
However, `pipenv-run RET ipython` works (not as interactive shell, as may be expected, but it find `ipython` at least).

**Comment by Pitometsu** [comment] 2018-01-21 14:33
Maybe, there's needed also something like `pipenv-exec` to run commands like scripts, but `pipenv-run` use for interactive shell only (not sure, which one it should be, iterm, or so).

**Comment by Pitometsu** [comment] 2018-01-21 14:35
Also, it would be good to check https://github.com/ionrock/pytest-el integration and, perhaps, python debugers for https://github.com/realgud/realgud.

**Comment by pwalsh** [comment] 2018-01-21 15:05
The [new function I added today for Flycheck integration](https://github.com/pwalsh/pipenv.el/blob/master/pipenv.el#L341) is likely part of the solution here.

@Pitometsu 

In the case of `run-python`, I assume you want `ipython` as the Python executable when a virtual environment is activated with `pipenv`, *if* `ipython` its present in the virtual environment. Correct?

It would be great if you can open distinct issues for (i) eldoc, (ii) pytest.el, and `realgud` integrations :).

**Comment by Pitometsu** [comment] 2018-01-21 15:11
`pipenv-where` – no otput, simple:
```
Finished /Users/netsu/Library/Python/2.7/bin/pipenv --where
```
in \*Messages\*.

**Comment by Pitometsu** [comment] 2018-01-21 15:18
https://github.com/pwalsh/pipenv.el/issues/10
https://github.com/pwalsh/pipenv.el/issues/11
https://github.com/pwalsh/pipenv.el/issues/12

**Comment by Pitometsu** [comment] 2018-01-21 15:24
Yes, it would be good to let `pipenv` auto-detect `ipython`, but not necessary (not everyone would like it). Just let it be in `exec-path` would be good enough.
Not sure, would be [that hacky approach](https://stackoverflow.com/a/16789182/3195266) be helpful here.

**Comment by pwalsh** [comment] 2018-01-23 19:48
Hey @Pitometsu can you give https://github.com/pwalsh/pipenv.el/commit/4e3216dd50014e3b293f454f90791b570962f720 a try? I think it may address this and other issues you have.

**Comment by Pitometsu** [comment] 2018-01-23 20:14
Tested, on both projects:
```
/Users/netsu/Projects/pt
Process Pipenv finished
/bin/python
Process Pipenv finished
No virtualenv has been created for this project yet!
Process Pipenv exited abnormally with code 1
```
In new version pipenv-* functions becomes available only after `M-x pipenv-mode` calling now.

**Comment by Pitometsu** [comment] 2018-01-23 20:16
`run-python` still don't see `ipython` in env.

**Comment by pwalsh** [comment] 2018-01-23 20:26
> In new version pipenv-* functions becomes available only after M-x pipenv-mode calling now.

Correct. See the updated README.

> Tested, on both projects (...)

I can't reproduce.

**Comment by Pitometsu** [comment] 2018-01-23 20:45
Try such project structure:
```
$ tree
.
├── Pipfile
├── Pipfile.lock
├── __init__.py
└── src
    └── test.py
```

**Comment by Pitometsu** [comment] 2018-01-23 21:00
looks like, pipenv runs not from project's root, but from current python file pwd.

**Comment by Pitometsu** [comment] 2018-01-23 21:09
`(pipenv-project?)` return right path.

**Comment by Pitometsu** [comment] 2018-01-23 21:53
Not sure, maybe use `start-file-process` instead of `make-process`?

**Comment by pwalsh** [comment] 2018-01-24 07:49
> looks like, pipenv runs not from project's root, but from current python file pwd.

`pipenv.el` does not manage that at all - [`pipenv` does](https://github.com/pypa/pipenv/blob/master/pipenv/project.py#L218)

> Not sure, maybe use start-file-process instead of make-process?

Not clear to me what problem that would solve (`start-file-process` calls `make-process`, and `make-process` sets current working directory to `default-directory` if the directory is local). Is there some detail of this that I am missing?

**Comment by Pitometsu** [comment] 2018-01-24 08:39
Than I don't know, what cause this…

**Comment by Pitometsu** [comment] 2018-02-08 10:18
Open `project-root/src/test.py`
- `M-x pipenv-mode`
- `C-x C-p s`

Output in `*Pipenv shell*`:
```
bash-4.4$ Creating a virtualenv for this project…
⠋Traceback (most recent call last):
  File "/Users/netsu/Library/Python/2.7/bin/pew", line 7, in <module>
    from pew.pew import pew
  File "/Users/netsu/Library/Python/2.7/lib/python/site-packages/pew/__init__.py", line 3, in <module>
    from . import pew
  File "/Users/netsu/Library/Python/2.7/lib/python/site-packages/pew/pew.py", line 41, in <module>
    from pew._utils import (check_call, invoke, expandpath, own, env_bin_dir,
  File "/Users/netsu/Library/Python/2.7/lib/python/site-packages/pew/_utils.py", line 20, in <module>
    locale.setlocale(locale.LC_CTYPE, '')
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

Virtualenv location: 
Spawning environment shell (/bin/bash). Use 'exit' to leave.
bash-3.2$ source /bin/activate
bash: /bin/activate: No such file or directory
bash-3.2$ 
```

**Comment by Pitometsu** [comment] 2018-02-08 10:22
Created same file at `project-root/test2.py`. Still same result.

**Comment by Pitometsu** [comment] 2018-02-08 10:23
But in plain bash:

```
Spawning environment shell (/bin/bash). Use 'exit' to leave.
bash-3.2$ source /Users/netsu/.local/share/virtualenvs/pt-DCu6CMh1/bin/activate
(pt-DCu6CMh1) bash-3.2$ exit
Yuriys-MacBook-Pro:pt netsu$ pipenv run ipython
Python 2.7.14 (default, Nov 14 2017, 19:52:12)
Type "copyright", "credits" or "license" for more information.

IPython 5.5.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]:
```

**Comment by Pitometsu** [comment] 2018-02-08 10:30
Looks like pipeenv.el doesn't see the Pipfile or so, doesn't it?

**Comment by Pitometsu** [comment] 2018-02-08 10:31
```
python-shell-virtualenv-root is a variable defined in ‘python.el’.
Its value is nil
```
```
python-shell-virtualenv-path is a variable defined in ‘python.el’.
Its value is nil
```

**Comment by Pitometsu** [comment] 2018-02-08 10:35
Furthermore!

I open `ansi-term` with bash, …and:
```
bash-4.4$ pipenv --venv
No virtualenv has been created for this project yet!
bash-4.4$ pwd
/Users/netsu/Projects/pt
bash-4.4$ ls
Pipfile  Pipfile.lock  __init__.py  src  test2.py
bash-4.4$ 
```

**Comment by Pitometsu** [comment] 2018-02-08 10:52
But in `zsh` in `ansi-term` all right:

```
Yuriys-MacBook-Pro% pipenv --venv
/Users/netsu/.local/share/virtualenvs/pt-DCu6CMh1
Yuriys-MacBook-Pro% 
```
It's pretty strange, because I have no zsh setup.

**Comment by pwalsh** [comment] 2018-02-08 10:56
@Pitometsu 

Having a bit of trouble following the long trail of comments ;).

But, I think, based on https://github.com/pwalsh/pipenv.el/issues/8#issuecomment-364070979 it seems the problem is elsewhere than `pipenev.el`. I'm keeping this issue open, but I have not yet heard from any others users with the same issue.

**Comment by Pitometsu** [comment] 2018-02-08 10:57
Looks like, I found cause of my problems:
```
bash-4.4$ source ~/.bash_profile
bash-4.4$ pipenv --venv
/Users/netsu/.local/share/virtualenvs/pt-DCu6CMh1
bash-4.4$ 
```
Somewhy `bash` in emacs require to be sourced from default profile…

**Comment by Pitometsu** [comment] 2018-02-08 11:08
My problem was in using `.bash_profile` instead of `.bashrc` for pipenv config. Sorry for noise :).

**Comment by Pitometsu** [comment] 2018-02-08 13:32
Damn, looks like, issue isn't solved for me yet.
For now `pipenv --venv` works in both *zsh* and *bash* in Emacs.
And doesn't at `eshell` or `pipenv.el`:
```
[Git@master] /Users/netsu/Projects/pt/src | 2018-02-08 15:22 
$ /Users/netsu/Library/Python/2.7/bin/pipenv --venv
No virtualenv has been created for this project yet!
```
```
Process Pipenv finished
No virtualenv has been created for this project yet!
```
BTW I'm on mac OS and use https://github.com/purcell/exec-path-from-shell to have bash environment in UI emacs. If I run (any, UI, or `-nw`) Emacs from bash in terminal – `pipenv` works.

It do not work only for graphical version launched outside bash login shell. Not sure that it related directly to `pipenv.el`, but, maybe, you have an idea, which env variables can I miss?

My dotfiles:
```
# .bash_profile
if [ -f $HOME/.bashrc ]; then
  source $HOME/.bashrc
fi

# pipenv completion
eval "$(pipenv --completion)"

# completions
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion
```
```
# .bashrc
export PATH="${HOME}/.local/bin:/usr/local/sbin:$PATH"
export GPG_TTY=$(tty)

# Docker
# eval $(docker-machine env default)

# Perl DBI
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Updated texinfo
export PATH="/usr/local/opt/texinfo/bin:$PATH"

# coreutils
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

# imagemagick
export PATH="/usr/local/opt/imagemagick@6/bin:$PATH"

# sqlite
export PATH="/usr/local/opt/sqlite/bin:$PATH"

# openssl
export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
# LDFLAGS="/usr/local/opt/openssl/lib:$LDFLAGS"
# CPPFLAGS="/usr/local/opt/openssl/include:CPPFLAGS"
# PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig:PKG_CONFIG_PATH"

# python
export PATH="/usr/local/opt/python/libexec/bin:$PATH"

# pipenv
export PATH="/Users/netsu/Library/Python/2.7/bin:$PATH"
```
```
# .zshrc
export PATH="${HOME}/.local/bin:/usr/local/sbin:$PATH"
export GPG_TTY=$(tty)

# Docker
# eval $(docker-machine env default)

# Perl DBI
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Updated texinfo
export PATH="/usr/local/opt/texinfo/bin:$PATH"

# coreutils
PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

# completions
fpath=(/usr/local/share/zsh-completions $fpath)

# Force rebuild zcomdump
# rm -f ~/.zcompdump; compinit

# In case of "zsh compinit: insecure directories"
# chmod go-w '/usr/local/share'
```

**Comment by pwalsh** [comment] 2018-02-08 13:40
Hey @Pitometsu 

This is really not a `pipenv.el` issue - it is one related to your own setup. I'd like to be able to help, but it is too specific to your setup. I use macOS too, and `exec-path-from-shell`, but my setup is quite specific to how I have my shell configured.

I'm going to close this issue again, but good luck with getting it sorted!

**Closed by pwalsh** 2018-02-08 13:40 UTC
Labels: enhancement, help wanted

**Comment by Pitometsu** [comment] 2018-02-08 14:19
Oh, I fixed it by myself by adding `LC_ALL` to `exec-path-from-shell-variables`.
