### ISSUE TITLE
Flycheck race condition with Projectile

### ISSUE THREAD

**Issue by tilgovi** [pwalsh/pipenv.el#19] opened 2018-03-25 20:19 UTC
If I switch projects (`C-c p p`) and then select a .py file, I correctly get a buffer with the right environment activated, the right flycheck executable paths, but all checkers disabled. Everything is fine if I open another Python file afterward. I suspect there's a race between when flycheck is enabled and when the executable path is updated, causing the checkers to be disabled on the first buffer.

Is there something that I might have misconfigured, is this expected, or is there something pipenv.el can do to toggle flycheck on/off or re-enable the Python checkers after hooking the executable path?

**Comment by pwalsh** [comment] 2018-03-26 06:43
@tilgovi thanks for the report. I'll check this, see if I can reproduce in a test, and issue a fix to ensure fly check is initialised correctly after pipenv.el changes contexts.

**Comment by pwalsh** [comment] 2018-12-06 16:31
https://github.com/pwalsh/pipenv.el/issues/45

**Comment by inpefess** [comment] 2019-03-02 20:22
The problem is deeper and not related to pipenv or projectile:

https://github.com/flycheck/flycheck/issues/1542

Flycheck doesn't update the enabled/disabled status of checkers. You can start with a venv with flake8 and then move to another venv without it. Then you'll get Python error 'flake8 not found' on every newline or even every change (depending on your flycheck configuration) because flycheck will have 'enabled' status for absent flake8.

So one possible workaround probably would be to add `flycheck-verify-checker` for Python checkers to `pipenv-activate`.

**Comment by pwalsh** [comment] 2019-03-03 15:52
Fixed in https://github.com/pwalsh/pipenv.el/pull/47

**Closed by pwalsh** 2019-03-03 15:52 UTC
Labels: bug
