### ISSUE TITLE
Fix pipenv-where and similar functions output

### ISSUE THREAD

**Issue by Pitometsu** [pwalsh/pipenv.el#13] opened 2018-01-21 15:19 UTC
`pipenv-where` – no output, simple:

```
Finished /Users/netsu/Library/Python/2.7/bin/pipenv --where
```

in \*Messages\*.

***

Maybe, there's needed also something like `pipenv-exec` to run commands like scripts, but `pipenv-run` use for interactive shell only (not sure, which one it should be, iterm, or so).

**Comment by pwalsh** [comment] 2018-01-21 15:23
@Pitometsu `pipenv.el` has its own buffer to log output at `*Pipenv*`, and `*Messages*` just logs that an action was made.

`*Pipenv*` needs some output formatting for sure, but I have not been concerned with that to present. If you could give a couple of examples that show formatting you might expect from `pipenv-where` etc. in the `*Pipenv*` buffer, it would be appreciated. Thanks!

**Comment by Pitometsu** [comment] 2018-01-21 15:32
Here's my outputs,
from \*Messages\*:

```
Finished /Users/netsu/Library/Python/2.7/bin/pipenv --where
Finished /Users/netsu/Library/Python/2.7/bin/pipenv --venv
```
from \*Pipenv\*:

```
/Users/netsu/Projects/csr
Process Pipenv finished
[31m[22mNo virtualenv has been created for this project yet![39m[22m
Process Pipenv exited abnormally with code 1
```
from bash for comparison:
```
$ pipenv --where
/Users/netsu/Projects/csr
$ pipenv --venv
/Users/netsu/.local/share/virtualenvs/csr-44kfYsMA
```
***
Expected output at *Pipenv*:

```
/Users/netsu/Projects/csr

/Users/netsu/.local/share/virtualenvs/csr-44kfYsMA

```

**Comment by pwalsh** [comment] 2018-01-21 15:40
@Pitometsu 

So the bad encoding in `*Pipenv*` was fixed in https://github.com/pwalsh/pipenv.el/commit/5ea277d81208fc1503b9dafe1ef4f90a89aeb095

The abnormal exit I can't reproduce.

Here is a fresh example from my machine:

shell:

```
bash-3.2$ ls
Dockerfile	Pipfile		README.org	pytest.ini
Makefile	Pipfile.lock	TODO.org	src
bash-3.2$ pipenv --where
/Users/pwalsh/Code/hamigdalor
bash-3.2$ pipenv --py
/Users/pwalsh/.local/share/virtualenvs/hamigdalor-oA7Am4f8/bin/python
bash-3.2$ pipenv --venv
/Users/pwalsh/.local/share/virtualenvs/hamigdalor-oA7Am4f8
```

*Messages*:

```
Switched to hamigdalor
Finished /usr/local/bin/pipenv --where
Finished /usr/local/bin/pipenv --py
Finished /usr/local/bin/pipenv --venv
```

*Pipenv*:

```
Process Pipenv finished
/Users/pwalsh/Code/hamigdalor
Process Pipenv finished
/Users/pwalsh/.local/share/virtualenvs/hamigdalor-oA7Am4f8/bin/python
Process Pipenv finished
/Users/pwalsh/.local/share/virtualenvs/hamigdalor-oA7Am4f8
Process Pipenv finished
```

**Comment by Pitometsu** [comment] 2018-01-21 15:53
```
Finished /Users/netsu/Library/Python/2.7/bin/pipenv --where
Finished /Users/netsu/Library/Python/2.7/bin/pipenv --py
Finished /Users/netsu/Library/Python/2.7/bin/pipenv --venv
```

```
/Users/netsu/Projects/csr
Process Pipenv finished
/bin/python
Process Pipenv finished
No virtualenv has been created for this project yet!
Process Pipenv exited abnormally with code 1
```
Now error message properly colored.

**Comment by Pitometsu** [comment] 2018-01-21 15:56
`python-activate` doing:

\*Messages*\
```
Finished /Users/netsu/Library/Python/2.7/bin/pipenv --py
```

\*Pipenv*\
```
Process Pipenv exited abnormally with code 1
```

**Comment by Pitometsu** [comment] 2018-01-21 15:59
```
$ pwd
/Users/netsu/Projects/csr
$ ls
Pipfile       README.md    __init__.pyc  data	    pytest.ini	   setup.py
Pipfile.lock  __init__.py  csr
$ pipenv --py
/Users/netsu/.local/share/virtualenvs/csr-44kfYsMA/bin/python
```

**Comment by pwalsh** [comment] 2018-01-21 16:08
@Pitometsu according to https://github.com/pwalsh/pipenv.el/issues/13#issuecomment-359258176 it is the `--venv` call that exits abnormally, not the `--py` one.

Also, you can see from your `*Messages*` that `pipenv.el` is simply calling `/Users/netsu/Library/Python/2.7/bin/pipenv --venv`. Is this the same executable as the one you find with `which pipenv`?

Do you have the same behaviour if you create a brand new virtual environment with Pipenv?

**Comment by Pitometsu** [comment] 2018-01-21 16:11
`(pipenv-venv)` actually raises `No virtualenv has been created for this project yet!`.

**Comment by Pitometsu** [comment] 2018-01-21 16:18
```
$ which pipenv
/Users/netsu/Library/Python/2.7/bin/pipenv
$ pipenv --venv
/Users/netsu/.local/share/virtualenvs/csr-44kfYsMA
$ ls -l ~/.virtualenvs
lrwxr-xr-x 1 netsu staff 37 Dec 15 10:32 /Users/netsu/.virtualenvs -> /Users/netsu/.local/share/virtualenvs
```

**Comment by Pitometsu** [comment] 2018-01-21 16:24
For buffer `M-! pwd` is `/Users/netsu/Projects/csr/csr/ic`
`M-: (projectile-project-root)` is `"/Users/netsu/Projects/csr/"`

**Comment by Pitometsu** [comment] 2018-01-21 16:27
Shouldn't `pipenv--command` use `(projectile-project-root)`?

**Comment by pwalsh** [comment] 2018-01-21 20:15
> For buffer M-! pwd is /Users/netsu/Projects/csr/csr/ic
> M-: (projectile-project-root) is "/Users/netsu/Projects/csr/"

I'm having troubling following your use case - how you are moving around, when you call commands, etc. `(pipenv-activate)` will try to activate *wherever you are*, just like calling `pipenv` directly will.

> Shouldn't pipenv--command use (projectile-project-root)?

No. There is no requirement to use Projectile. I could force commands to execute at the location of `Pipfile`, in Emacs, but, we are just passing the command to `pipenv`, and it does not require this. 


-----

As I asked in https://github.com/pwalsh/pipenv.el/issues/13#issuecomment-359259322 

> (d)o you have the same behaviour if you create a brand new virtual environment with Pipenv?

**Comment by Pitometsu** [comment] 2018-01-21 20:38
```
$ mkdir -p pt/src
$ cd pt
$ touch Pipfile
$ touch __init__.py
$ git init
Initialized empty Git repository in /Users/netsu/Projects/pt/.git/
$ pipenv install ipython -d
Creating a virtualenv for this project…
⠋New python executable in /Users/netsu/.local/share/virtualenvs/pt-DCu6CMh1/bin/python2.7
Also creating executable in /Users/netsu/.local/share/virtualenvs/pt-DCu6CMh1/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/netsu/.local/share/virtualenvs/pt-DCu6CMh1
( . . . )
Installing ipython…
Updated Pipfile.lock (33647b)!
$ echo "from IPython import embed; embed()" > src/test.py
$ pipenv --where
/Users/netsu/Projects/pt
$ pipenv --py
/Users/netsu/.local/share/virtualenvs/pt-DCu6CMh1/bin/python
$ pipenv --venv
/Users/netsu/.local/share/virtualenvs/pt-DCu6CMh1
$ pipenv run ipython
Python 2.7.14 (default, Nov 14 2017, 19:52:12)
Type "copyright", "credits" or "license" for more information.

IPython 5.5.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]:
```
Now, in Emacs:
```
C-x C-f pt/src/test.py
M-x pipenv-where ;; => /Users/netsu/Projects/pt
M-x pipenv-py ;; => /bin/python (?!!)
M-x pipenv-venv ;; => No virtualenv has been created for this project yet!
```

**Comment by pwalsh** [comment] 2018-01-25 07:12
So the actual issue of output is fine: `pipenv.el` outputs to *Messages* and *Pipenv* in a way that is expected at present. The other issues are about errors that @Pitometsu that I currently cannot reproduce, and which are also in discussion [here](https://github.com/pwalsh/pipenv.el/issues/8). Closing this issue.

**Closed by pwalsh** 2018-01-25 07:12 UTC
Labels: enhancement, help wanted
